apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gradientzoo-web-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - secretName: gradientzoo-web-tls
      hosts:
        - gradientzoo.com
        - www.gradientzoo.com
  backend:
    serviceName: gradientzoo-web-svc
    servicePort: 3000
  rules:
  - host: www.gradientzoo.com
    http:
      paths:
      - path: /
        backend:
          serviceName: gradientzoo-web-svc
          servicePort: 3000
  - host: gradientzoo.com
    http:
      paths:
      - path: /
        backend:
          serviceName: gradientzoo-web-svc
          servicePort: 3000
